# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(536, 260)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.input_field = QtWidgets.QLineEdit(self.centralwidget)
        self.input_field.setGeometry(QtCore.QRect(30, 110, 113, 20))
        self.input_field.setObjectName("input_field")
        self.list_widget = QtWidgets.QComboBox(self.centralwidget)
        self.list_widget.setGeometry(QtCore.QRect(160, 110, 69, 22))
        self.list_widget.setObjectName("list_widget")
        self.list_widget.addItem("")
        self.list_widget.addItem("")
        self.date_edit = QtWidgets.QDateEdit(self.centralwidget)
        self.date_edit.setGeometry(QtCore.QRect(250, 110, 121, 22))
        self.date_edit.setObjectName("date_edit")
        self.title_main = QtWidgets.QLabel(self.centralwidget)
        self.title_main.setGeometry(QtCore.QRect(50, 30, 201, 16))
        self.title_main.setObjectName("title_main")
        self.push_to_csv = QtWidgets.QPushButton(self.centralwidget)
        self.push_to_csv.setGeometry(QtCore.QRect(390, 110, 75, 23))
        self.push_to_csv.setObjectName("push_to_csv")
        self.but_hist = QtWidgets.QPushButton(self.centralwidget)
        self.but_hist.setGeometry(QtCore.QRect(70, 160, 81, 21))
        self.but_hist.setObjectName("but_hist")
        self.but_anal = QtWidgets.QPushButton(self.centralwidget)
        self.but_anal.setGeometry(QtCore.QRect(180, 160, 75, 23))
        self.but_anal.setObjectName("but_anal")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 536, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.list_widget.setItemText(0, _translate("MainWindow", "расходы"))
        self.list_widget.setItemText(1, _translate("MainWindow", "доходы"))
        self.title_main.setText(_translate("MainWindow", "Учет расходов и доходов семьи"))
        self.push_to_csv.setText(_translate("MainWindow", "добавить"))
        self.but_hist.setText(_translate("MainWindow", "история"))
        self.but_anal.setText(_translate("MainWindow", "анализ"))
